version: '3.9'

services:
  golang_study:
    container_name: golang_study
    image: golang:1.20
    volumes:
      - .:/go/src
    ports:
      - 8080:8080
    command: tail -f "/dev/null"
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - .database:/data/db
    ports:
      - 27017:27017